on: [push, pull_request]
name: CI
jobs:
  test:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing weaviate-racket-client and its dependencies
        run: raco pkg install --no-docs --auto --name weaviate-racket-client
      - name: Compiling weaviate-racket-client and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps weaviate-racket-client
      - name: Start test server
        run: ci/run_dependencies.sh
      - name: Run tests
        run: raco test -x -p weaviate-racket-client
      - name: Stop test server
        run: ci/stop_dependencies.sh
